spring.application.name=externo-ms
stripe.api.key=${STRIPE_API_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}
scb.mailgun.domain=${MAILGUN_DOMAIN}
scb.mailgun.from=${MAILGUN_FROM}
scb.mailgun.api-key=${MAILGUN_API_KEY}
logging.level.com.scb.externo.gateway=INFO