spring.application.name=externo-ms
stripe.api.key=${STRIPE_API_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}
mailgun.api.key=${MAILGUN_API_KEY}
mailgun.domain=${MAILGUN_DOMAIN}
mailgun.from=${MAILGUN_FROM}